[fix] Update caret position when SM is opened/closed
storytouch/ep_cursortrace pull request #3
Opened 2018-07-06 18:09 UTC by lpagliari

This fix also work when for:

- changes on the browser zoom;
- editing a line and making it longer (and increasing its height on the screen), pulling the following lines further down;
- pasting content above the line where caret is.

Depends on [this PR of ep_comments](https://github.com/storytouch/ep_comments/pull/33).

Fixes bug https://trello.com/c/SgiGE4V0/1377.

2018-07-06 18:11 UTC, lpagliari commented on static/js/main.js
> +var pendingCaretLocations = {};
Guardamos as posições dos carets que já estão sendo mostrados no editor (`currentCaretLocations`) e os que estão aguardando na fila para serem mostrados (`pendingCaretLocations`) -- esses últimos só são usados enquanto o editor é carregado.

2018-07-06 18:12 UTC, lpagliari commented on static/js/main.js
> +  var $indicator = $("<div " + classes + " timestamp="+timestamp+"><p>"+authorName+"</p></div>");
Usamos essa _timestamp_ para ficar mais fácil de detectar quando o caret foi atualizado no padOuter

2018-07-10 14:18 UTC, joassouza requested changes

2018-07-10 14:18 UTC, joassouza commented on static/js/main.js
> +    sendMessageWithCaretPosition(lastPositionOfMyCaret[0], lastPositionOfMyCaret[1]);
o que é cada lastPositionOfMyCaret? Linha, coluna?

2018-07-10 14:18 UTC, joassouza commented on static/tests/frontend/specs/integration-ep_sm.js
> +    var script = lineBeforeSM + separator + synopsis + heading + separator + lineAfterSM;
👍

2018-07-10 14:18 UTC, joassouza commented on static/tests/frontend/specs/integration-ep_sm.js
> +  context('when other user places caret on a line before a SM hidden for this user', function() {
boa!

2018-07-10 14:18 UTC, joassouza commented on static/tests/frontend/specs/integration-ep_sm.js
> +      it('does not update the caret indicator', function(done) {
se eu entendi direito, quando um usuário abre um SM o caret não muda de posição?

2018-07-10 14:18 UTC, joassouza commented on static/tests/frontend/specs/integration-ep_sm.js
> +      it('keeps the caret indicator on the right position', function(done) {
talvez fosse melhor escrever o que é a `right position`. Nesse caso aqui `LINE_BEFORE_SM`? Lendo só as descrições ficaria mais fácil de entender o cenário

2018-07-10 14:18 UTC, joassouza commented on static/tests/frontend/specs/integration-ep_sm.js
> +      it('keeps the caret indicator on the right position', function(done) {
melhor, escrever algo como `proper position` ?

2018-07-10 15:24 UTC, lpagliari commented on static/js/main.js
> +    sendMessageWithCaretPosition(lastPositionOfMyCaret[0], lastPositionOfMyCaret[1]);
É, tb achei horrível isso de guardar posição em um array. Já mudei isso no código, deve ir no próximo PR.

2018-07-10 15:26 UTC, lpagliari commented on static/tests/frontend/specs/integration-ep_sm.js
> +      it('does not update the caret indicator', function(done) {
@joassouza sim, mas apenas no caso do caret estar *antes* da linha da SM -- abrir ou fechá-la não vai mudar sua posição nesse caso

2018-07-10 16:59 UTC, merged